# 모델 저장과 복원
---
- 방법 1) 모델 전체 저장(모델 구조, 가중치, 변수, ...)
    - save_model()
    - 복원 시 추가 작업이 필요없고, 모델 파일만 로딩해서 사용 가능
- 방법 2) 가중치만 저장
    - save_weights()
    - 복원 시 모델 구조(Architechture) 생성 후 가중치 적용
- 방법 3) 모델 전체 또는 가중치 자동 저장
    - fit()에서 ModelCheckPoint Event에 대한 callback 등록
    - save_best_only=True : 모니터링 기준에 따라서 좋은 성능의 모델만 저장
    - save_weight_only=True : 가중치만 저장
- 파일 또는 폴더로 저장
    - 파일 확장자가 없을 시 폴더로 저장됨
    - 파일 확장자
        - h5 / hdf5 : HDF5 포맷으로 모델 또는 가중치 저장
        - ckpf : 체크포인트 파일 형태로 저장
        - pd : 모델 저장

In [317]:
from sklearn.datasets import load_iris
from keras import Sequential
from keras.layers import Dense
from keras.utils import set_random_seed, plot_model
from keras.models import save_model, load_model
from sklearn.preprocessing import OneHotEncoder, MinMaxScaler
from sklearn.model_selection import train_test_split
import warnings

warnings.filterwarnings('ignore')
set_random_seed(42)

# 데이터 준비 및 로딩 / 모델 생성

In [303]:
df = load_iris()
x_train = df.data
y_train = df.target
x_train.shape, y_train.shape

((150, 4), (150,))

In [304]:
df.target_names, df.feature_names

(array(['setosa', 'versicolor', 'virginica'], dtype='<U10'),
 ['sepal length (cm)',
  'sepal width (cm)',
  'petal length (cm)',
  'petal width (cm)'])

In [305]:
# encoder = OneHotEncoder()
# encoder.fit([y_train])
# encoder.transform([y_train])

In [306]:
scaler = MinMaxScaler()
scaler.fit(x_train)
scaler.transform(x_train)

array([[0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.11111111, 0.5       , 0.05084746, 0.04166667],
       [0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.19444444, 0.66666667, 0.06779661, 0.04166667],
       [0.30555556, 0.79166667, 0.11864407, 0.125     ],
       [0.08333333, 0.58333333, 0.06779661, 0.08333333],
       [0.19444444, 0.58333333, 0.08474576, 0.04166667],
       [0.02777778, 0.375     , 0.06779661, 0.04166667],
       [0.16666667, 0.45833333, 0.08474576, 0.        ],
       [0.30555556, 0.70833333, 0.08474576, 0.04166667],
       [0.13888889, 0.58333333, 0.10169492, 0.04166667],
       [0.13888889, 0.41666667, 0.06779661, 0.        ],
       [0.        , 0.41666667, 0.01694915, 0.        ],
       [0.41666667, 0.83333333, 0.03389831, 0.04166667],
       [0.38888889, 1.        , 0.08474576, 0.125     ],
       [0.30555556, 0.79166667, 0.05084746, 0.125     ],
       [0.22222222, 0.625     ,

In [307]:
x_train = x_train.reshape(-1, 4)
# y_train = y_train.reshape(-1, 1)

In [308]:
x_train, x_test, y_train, y_test = train_test_split(x_train, y_train,
                                                    test_size=0.2,
                                                    random_state=42)

In [309]:
model = Sequential()

In [310]:
model.add(Dense(10, activation='relu', input_shape=(4,)))
model.add(Dense(10, activation='relu'))
model.add(Dense(10, activation='relu'))
model.add(Dense(3, activation='softmax'))

In [311]:
model.compile(loss='sparse_categorical_crossentropy', metrics='accuracy',
              optimizer='adam')

In [312]:
model.fit(x_train, y_train, epochs=200)

Epoch 1/200
4/4 [==============================] - 0s 1ms/step - loss: 1.1651 - accuracy: 0.3250
Epoch 2/200
4/4 [==============================] - 0s 1ms/step - loss: 1.1414 - accuracy: 0.3250
Epoch 3/200
4/4 [==============================] - 0s 1ms/step - loss: 1.1264 - accuracy: 0.3250
Epoch 4/200
4/4 [==============================] - 0s 1ms/step - loss: 1.1124 - accuracy: 0.3250
Epoch 5/200
4/4 [==============================] - 0s 1ms/step - loss: 1.0996 - accuracy: 0.3250
Epoch 6/200
4/4 [==============================] - 0s 1ms/step - loss: 1.0899 - accuracy: 0.3250
Epoch 7/200
4/4 [==============================] - 0s 1000us/step - loss: 1.0806 - accuracy: 0.3250
Epoch 8/200
4/4 [==============================] - 0s 1ms/step - loss: 1.0717 - accuracy: 0.3000
Epoch 9/200
4/4 [==============================] - 0s 2ms/step - loss: 1.0624 - accuracy: 0.2083
Epoch 10/200
4/4 [==============================] - 0s 2ms/step - loss: 1.0517 - accuracy: 0.1000
Epoch 11/200
4/4 [========

In [313]:
model.predict(x_test[:5])

1/1 [==============================] - 0s 43ms/step


array([[3.6857653e-04, 9.8482937e-01, 1.4802096e-02],
       [9.9989367e-01, 1.0576563e-04, 5.6764662e-07],
       [9.2860762e-12, 1.6156935e-05, 9.9998379e-01],
       [2.6981471e-04, 9.5124400e-01, 4.8486233e-02],
       [2.0289513e-04, 9.7897971e-01, 2.0817349e-02]], dtype=float32)

In [314]:
y_test[:5]

array([1, 0, 2, 1, 1])

# 모델 저장

In [315]:
loss_value, accuracy_value = model.evaluate(x_test, y_test)

1/1 [==============================] - 0s 88ms/step - loss: 0.0810 - accuracy: 0.9667


In [316]:
M_FILE = r'irisModel.h5'
W_FILE = r'irisWeight.h5'
if accuracy_value >= 0.96:
    save_model(model, M_FILE)
    model.save_weights(W_FILE)

# 모델 복원
- load_model(모델 파일 또는 모델 폴더명)
- Sequential.load_weights(가중치 파일 또는 폴더명)

In [320]:
# 모델 복원
model_new = load_model(r'./irisModel.h5')
model_new.summary()

Model: "sequential_22"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_88 (Dense)            (None, 10)                50        
                                                                 
 dense_89 (Dense)            (None, 10)                110       
                                                                 
 dense_90 (Dense)            (None, 10)                110       
                                                                 
 dense_91 (Dense)            (None, 3)                 33        
                                                                 
Total params: 303
Trainable params: 303
Non-trainable params: 0
_________________________________________________________________


In [325]:
# 가중치 복원(구조는 똑같아야함)
new_model = Sequential()
new_model.add(Dense(10, activation='relu', input_shape=(4,)))
new_model.add(Dense(10, activation='relu'))
new_model.add(Dense(10, activation='relu'))
new_model.add(Dense(3, activation='softmax'))
new_model.load_weights(W_FILE)

new_model.compile(loss='sparse_categorical_crossentropy', metrics='accuracy',
                  optimizer='adam')

In [326]:
new_model.evaluate(x_test, y_test)

1/1 [==============================] - 0s 134ms/step - loss: 0.0810 - accuracy: 0.9667


[0.08103922754526138, 0.9666666388511658]